### ISSUE TITLE
gffutils database build failed with No lines parsed

### ISSUE THREAD

**Issue by yyliang12** [Kuanhao-Chao/LiftOn#25]
Hi

There is a problem when I using `Lifton` to lift-over the annotation from the reference to another same species.
I got `miniprot` installed on my machine already and settled in environment variable as well.
```bash
$ which miniprot
~/usr/bin/miniprot
```
The command that I used was:
```bash
lifton --threads 5 -g ref_genome.gff3 -o asm_lifton.gff3 -copies asm.fa ref_genome.fa
```
But no matter how I've tried to `export PATH` or sth else , the problem:
```plain
**********************
** Running miniprot **
**********************
gffutils database build failed with No lines parsed -- was an empty file provided?
gffutils database build failed with No lines parsed -- was an empty file provided?
```
always keep popping up.
How can I solve this?

Thanks,
Yanyang.

**Comment by yyliang12** [comment]
Hi Kuanhao,

The above problems may be due to operational errors.
After I changing everything into realpath then the program can run normally.
But then another issue showed up while writing the final lifton GFF file, which is
```python
>> LiftOn processed: 5440 features.
>> LiftOn processed: 5460 features.
>> LiftOn processed: 5480 features.
>> LiftOn processed: 5500 features.
>> LiftOn processed: 5520 features.Traceback (most recent call last):
  File "/home/yanyang_liang/miniconda3/bin/lifton", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/yanyang_liang/miniconda3/lib/python3.11/site-packages/lifton/lifton.py", line 352, in main
    run_all_lifton_steps(args)
  File "/home/yanyang_liang/miniconda3/lib/python3.11/site-packages/lifton/lifton.py", line 302, in run_all_lifton_steps
    if lifton_gene is None or lifton_gene.ref_gene_id is None:
                              ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'LiftOn_FEATURE' object has no attribute 'ref_gene_id'. Did you mean: 'ref_tran_id'?
```
I got 12 of my sample genomes into test and 5 of them met the same problem.
Any helps are appreciated.

Thanks,
Yanyang.

**Comment by Kuanhao-Chao** [comment]
The primary cause (seqid/realpath mismatch) now raises a clear error at startup (#34). The secondary AttributeError is guarded on current `devel`. Please re-run on ≥ **v1.0.10**; if the AttributeError persists, share the command + a snippet of the reference GFF.
