### ISSUE TITLE
parasail_memalign: posix_memalign failed: Cannot allocate memory

### ISSUE THREAD

**Issue by celinehohzm** [Kuanhao-Chao/LiftOn#9]
Hi, 

I'm trying to liftover the CHESS_GRch38 annotation to CHM13 using this command 

`lifton -D -g /ccb/salz3/kh.chao/ref_genome/homo_sapiens/chess/chess3.0.1.gff_db -o /ccb/salz2/kh.chao/LiftOn/results/human_chess/lifton.gff3 --liftoff /ccb/salz2/kh.chao/LiftOn/results/human_chess/lifton_output/liftoff/liftoff.gff3_polished_db --miniprot /ccb/salz2/kh.chao/LiftOn/results/human_chess/lifton_output/miniprot/miniprot.gff3_db --proteins /ccb/salz2/kh.chao/LiftOn/results/human_chess/lifton_output/intermediate_files/proteins.fa --transcripts /ccb/salz2/kh.chao/LiftOn/results/human_chess/lifton_output/intermediate_files/transcripts.fa -polish -copies -sc 0.95 /ccb/salz3/kh.chao/ref_genome/homo_sapiens/T2T-CHM13/chm13v2.0.fa /ccb/salz3/kh.chao/ref_genome/homo_sapiens/chess/hg38_p12_ucsc.no_alts.no_fixs.fa -chroms /ccb/salz2/kh.chao/LiftOn/scripts/human_chroms_mapping.csv -f /ccb/salz2/kh.chao/LiftOn/scripts/features.txt`

Lifton was able to run for a bit and populate features but I soon encounter this error 
```
 parasail_memalign: posix_memalign failed: Cannot allocate memory
parasail_result_is_saturated: missing result
parasail_result_is_trace: missing result
Traceback (most recent call last):
  File "/home/choh1/anaconda3/envs/intron/bin/lifton", line 33, in <module>
    sys.exit(load_entry_point('lifton==1.0.3', 'console_scripts', 'lifton')())
  File "/home/choh1/anaconda3/envs/intron/lib/python3.9/site-packages/lifton/lifton.py", line 352, in main
    run_all_lifton_steps(args)
  File "/home/choh1/anaconda3/envs/intron/lib/python3.9/site-packages/lifton/lifton.py", line 300, in run_all_lifton_steps
    lifton_gene = run_liftoff.process_liftoff(None, locus, ref_db.db_connection, l_feature_db, ref_id_2_m_id_trans_dict, m_feature_db, tree_dict, tgt_fai, ref_proteins, ref_trans, ref_features_dict, fw_score, fw_chain, args, ENTRY_FEATURE=True)
  File "/home/choh1/anaconda3/envs/intron/lib/python3.9/site-packages/lifton/run_liftoff.py", line 176, in process_liftoff
    lifton_trans_aln, lifton_aa_aln = lifton_gene.orf_search_protein(lifton_trans.entry.id, ref_trans_id, tgt_fai, ref_proteins, ref_trans, lifton_status)
  File "/home/choh1/anaconda3/envs/intron/lib/python3.9/site-packages/lifton/lifton_class.py", line 145, in orf_search_protein
    lifton_aln, good_trans = self.transcripts[trans_id].orf_search_protein(fai, ref_protein_seq, ref_trans_seq, lifton_status, is_non_coding=self.is_non_coding, eval_only=eval_only)
  File "/home/choh1/anaconda3/envs/intron/lib/python3.9/site-packages/lifton/lifton_class.py", line 531, in orf_search_protein
    lifton_tran_aln = self.align_trans_seq(trans_seq, ref_trans_seq, lifton_status)
  File "/home/choh1/anaconda3/envs/intron/lib/python3.9/site-packages/lifton/lifton_class.py", line 522, in align_trans_seq
    lifton_tran_aln = align.trans_align(trans_seq, ref_trans_seq)
  File "/home/choh1/anaconda3/envs/intron/lib/python3.9/site-packages/lifton/align.py", line 122, in trans_align
    alignment_query = extracted_parasail_res.traceback.query
  File "/home/choh1/anaconda3/envs/intron/lib/python3.9/site-packages/parasail/bindings_v2.py", line 422, in traceback
    return self.get_traceback()
  File "/home/choh1/anaconda3/envs/intron/lib/python3.9/site-packages/parasail/bindings_v2.py", line 406, in get_traceback
    raise AttributeError("'Result' object has no traceback")
AttributeError: 'Result' object has no traceback
parasail_result_free: attempted free of NULL result pointer
```
Any suggestions would be greatly appreciated, thank you!

**Comment by Kuanhao-Chao** [comment]
Fixed in **v1.0.10**, now on PyPI.

The crash was O(L²) memory in the full-DP protein/DNA aligner on giant genes (titin-scale). LiftOn now routes any sequence above ~2500 aa / 8000 nt through an anchor-windowed aligner (`lifton/align.py` → `lifton/windowed_align.py`), cutting peak RSS ~17× (44.9 GB → 2.6 GB on the mouse benchmark) with identical alignments wherever anchors exist.

```
pip install -U lifton
```

Closing — please reopen if it recurs.
